name: CI

on:
  # push:
  #   branches: [ main ]
  # pull_request:
  #   branches: [ main ]

  workflow_dispatch:
  schedule:
      - cron:  '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v5
      with:
        go-version: 'stable'
        cache-dependency-path: "**/*.sum"
    - uses: actions/setup-java@v4
      with:
        distribution: 'oracle'
        java-version: '21'

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: |
          # ~/go1.25.0.linux-amd64.tar.gz
          # ~/jdk-8u331-linux-x64.tar.gz
          ~/lua-5.1.5.tar.gz
          ~/v2.1.0-beta3.tar.gz
        key: ${{ runner.os }}-${{ hashFiles('~/*.tar.gz') }}
        restore-keys: |
          ${{ runner.os }}-

    - name: free
      run: free

    - name: Set up Go
      run: |
        go version

    - name: Set up Java
      run: |
        javac -version
        # https://docs.oracle.com/javase/8/docs/technotes/guides/vm/gctuning/parallel.html#default_heap_size
        java -XX:+PrintFlagsFinal -version | grep MaxHeapSize

    - name: Set up Lua
      run: |
        sudo apt-get update
        sudo apt-get install -y libreadline-dev
        cd ~
        if [ ! -f lua-5.1.5.tar.gz ]
        then
          curl -O https://www.lua.org/ftp/lua-5.1.5.tar.gz
        fi
        tar xzf lua-5.1.5.tar.gz
        cd lua-5.1.5
        sudo make linux install
        lua -v

    - name: Set up LuaJIT
      run: |
        cd ~
        if [ ! -f v2.1.0-beta3.tar.gz ]
        then
          curl -LO https://github.com/LuaJIT/LuaJIT/archive/refs/tags/v2.1.0-beta3.tar.gz
        fi
        tar xzf v2.1.0-beta3.tar.gz
        cd LuaJIT-2.1.0-beta3
        make && sudo make install
        sudo ln -sf luajit-2.1.0-beta3 /usr/local/bin/luajit
        luajit -v

    - name: Set up hyperfine
      run: |
        wget https://github.com/sharkdp/hyperfine/releases/download/v1.19.0/hyperfine_1.19.0_amd64.deb
        sudo dpkg -i hyperfine_1.19.0_amd64.deb

    - name: bench
      run: |
        . ~/.profile
        ./bench
