name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Lua
      run: |
        curl -O https://www.lua.org/ftp/lua-5.1.5.tar.gz
        tar xzf lua-5.1.5.tar.gz
        cd lua-5.1.5
        sudo make linux install

    - name: bench
      run: ./bench
