name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/lua-5.1.5.tar.gz
          ~/companyfacts.zip
        key: ${{ runner.os }}-${{ hashFiles('~/**') }}

    - name: Set up Lua
      run: |
        cd ~
        if [ ! -f lua-5.1.5.tar.gz ]
        then
          curl -O https://www.lua.org/ftp/lua-5.1.5.tar.gz
        fi
        tar xzf lua-5.1.5.tar.gz
        cd lua-5.1.5
        sudo make linux install

    - name: Set up EDGAR API bulk data
      run: |
        cd ~
        if [ ! -f companyfacts.zip ]
        then
          curl \
          -H "User-Agent: Andrew McWatters & Co. github@andrewmcwatters.com" \
          -H "Accept-Encoding: gzip, deflate" \
          -H "Host: www.sec.gov" \
          -O \
          https://www.sec.gov/Archives/edgar/daily-index/xbrl/companyfacts.zip
        fi
        unzip companyfacts.zip
        ls -la

    - name: bench
      run: ./bench
