name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/lua-5.1.5.tar.gz
          ~/go1.18.1.linux-amd64.tar.gz
          ~/jdk-8u321-linux-x64.tar.gz
          ~/companyfacts.zip
        key: ${{ runner.os }}-${{ hashFiles('~/**') }}
        restore-keys: |
          ${{ runner.os }}-

    - name: Set up Lua
      run: |
        cd ~
        if [ ! -f lua-5.1.5.tar.gz ]
        then
          curl -O https://www.lua.org/ftp/lua-5.1.5.tar.gz
        fi
        tar xzf lua-5.1.5.tar.gz
        cd lua-5.1.5
        sudo make linux install
        lua -v

    - name: Set up Go
      run: |
        cd ~
        if [ ! -f go1.18.1.linux-amd64.tar.gz ]
        then
          curl -LO https://go.dev/dl/go1.18.1.linux-amd64.tar.gz
        fi
        sudo rm $(which go) && sudo tar -C /usr/local -xzf go1.18.1.linux-amd64.tar.gz
        echo 'export PATH=$PATH:/usr/local/go/bin' >> .profile
        source $HOME/.profile
        go version

    - name: Set up Java
      run: |
        cd ~
        if [ ! -f jdk-8u321-linux-x64.tar.gz ]
        then
          curl -LO https://github.com/andrewmcwattersandco/programming-language-benchmarks/releases/download/jdk-8u321-linux-x64/jdk-8u321-linux-x64.tar.gz
        fi
        tar zxf jdk-8u321-linux-x64.tar.gz
        echo 'export PATH=/usr/local/jdk1.8.0_321/bin:$PATH' >> .profile
        . .profile
        java -version

    - name: Set up EDGAR API bulk data
      run: |
        cd ~
        if [ ! -f companyfacts.zip ]
        then
          curl \
            -H "User-Agent: Sample Company Name AdminContact@<sample company domain>.com" \
            -H "Accept-Encoding: gzip, deflate" \
            -H "Host: www.sec.gov" \
            -O \
            https://www.sec.gov/Archives/edgar/daily-index/xbrl/companyfacts.zip
        fi
        unzip -q companyfacts.zip -d ${{ github.workspace }}/json/companyfacts
        ls -la

    - name: bench
      run: ./bench -v
